name: Check docs

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  check_docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: ni/python-actions/setup-python@dee640bba235ae28fdc6b7337c643bd06358ae90 # v0.9.0
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@dee640bba235ae28fdc6b7337c643bd06358ae90 # v0.9.0
      - name: Check for lock changes
        run: poetry check --lock
      - name: Cache virtualenv (with docs)
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .venv
          key: hightime-with-docs-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install hightime (with docs)
        run: poetry install -v --only main,docs
      - name: Generate docs
        run:  poetry run sphinx-build docs docs/_build -b html -W
      - name: Upload docs artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: hightime-docs
          path: docs/_build/
