name: Check hightime

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  check_hightime:
    name: Check hightime
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: ni/python-actions/setup-python@dee640bba235ae28fdc6b7337c643bd06358ae90 # v0.9.0
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@dee640bba235ae28fdc6b7337c643bd06358ae90 # v0.9.0
      - name: Check for lock changes
        run: poetry check --lock
      - name: Cache virtualenv
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .venv
          key: hightime-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install hightime
        run: poetry install -v
      - name: Lint
        run: poetry run ni-python-styleguide lint
      - name: Mypy static analysis (Linux)
        run:  poetry run mypy
      - name: Mypy static analysis (Windows)
        run:  poetry run mypy --platform win32
      - name: Bandit security checks
        run:  poetry run bandit -c pyproject.toml -r hightime
      # - name: Add virtualenv to the path for pyright-action
      #   run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      # - name: Pyright static analysis (Linux)
      #   uses: jakebailey/pyright-action@b5d50e5cde6547546a5c4ac92e416a8c2c1a1dfe # v2.3.2
      #   with:
      #     python-platform: Linux
      #     version: PATH
      # - name: Pyright static analysis (Windows)
      #   uses: jakebailey/pyright-action@b5d50e5cde6547546a5c4ac92e416a8c2c1a1dfe # v2.3.2
      #   with:
      #     python-platform: Windows
      #     version: PATH
